/**
 * 业务规则常量定义
 *
 * @description 定义业务规则相关的常量
 * @since 1.0.0
 */

/**
 * 业务规则常量
 */
export const BusinessRules = {
  // 租户规则
  TENANT_NAME_MIN_LENGTH: 3,
  TENANT_NAME_MAX_LENGTH: 100,
  TENANT_DESCRIPTION_MAX_LENGTH: 500,

  // 组织规则
  ORGANIZATION_NAME_MIN_LENGTH: 2,
  ORGANIZATION_NAME_MAX_LENGTH: 100,
  ORGANIZATION_DESCRIPTION_MAX_LENGTH: 500,

  // 部门规则
  DEPARTMENT_NAME_MIN_LENGTH: 2,
  DEPARTMENT_NAME_MAX_LENGTH: 100,
  DEPARTMENT_DESCRIPTION_MAX_LENGTH: 500,
  DEPARTMENT_MAX_LEVEL: 10,

  // 用户规则
  USERNAME_MIN_LENGTH: 3,
  USERNAME_MAX_LENGTH: 50,
  USERNAME_PATTERN: /^[a-zA-Z0-9_]+$/,
  EMAIL_PATTERN: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
  PHONE_PATTERN: /^1[3-9]\d{9}$/,
  PASSWORD_MIN_LENGTH: 8,
  PASSWORD_MAX_LENGTH: 128,
  DISPLAY_NAME_MIN_LENGTH: 1,
  DISPLAY_NAME_MAX_LENGTH: 100,

  // 角色规则
  ROLE_NAME_MIN_LENGTH: 2,
  ROLE_NAME_MAX_LENGTH: 50,
  ROLE_DESCRIPTION_MAX_LENGTH: 500,

  // 权限规则
  PERMISSION_NAME_MIN_LENGTH: 2,
  PERMISSION_NAME_MAX_LENGTH: 100,
  PERMISSION_DESCRIPTION_MAX_LENGTH: 500,
} as const;

/**
 * 状态常量
 */
export const StatusConstants = {
  // 通用状态
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  LOCKED: "LOCKED",
  DISABLED: "DISABLED",
  PENDING: "PENDING",
  DELETED: "DELETED",

  // 租户状态
  TENANT_ACTIVE: "ACTIVE",
  TENANT_INACTIVE: "INACTIVE",
  TENANT_SUSPENDED: "SUSPENDED",
  TENANT_PENDING: "PENDING",

  // 用户状态
  USER_ACTIVE: "ACTIVE",
  USER_INACTIVE: "INACTIVE",
  USER_LOCKED: "LOCKED",
  USER_DISABLED: "DISABLED",
  USER_PENDING: "PENDING",

  // 组织状态
  ORGANIZATION_ACTIVE: "ACTIVE",
  ORGANIZATION_INACTIVE: "INACTIVE",
  ORGANIZATION_SUSPENDED: "SUSPENDED",

  // 部门状态
  DEPARTMENT_ACTIVE: "ACTIVE",
  DEPARTMENT_INACTIVE: "INACTIVE",
  DEPARTMENT_SUSPENDED: "SUSPENDED",
} as const;
