/**
 * 错误相关常量定义
 *
 * @description 定义错误代码和错误相关的常量
 * @since 1.0.0
 */

/**
 * 错误代码常量
 */
export const ErrorCodes = {
  // 通用错误代码
  VALIDATION_FAILED: "VALIDATION_FAILED",
  BUSINESS_RULE_VIOLATION: "BUSINESS_RULE_VIOLATION",
  ENTITY_NOT_FOUND: "ENTITY_NOT_FOUND",
  DUPLICATE_ENTITY: "DUPLICATE_ENTITY",
  INVALID_STATE: "INVALID_STATE",
  PERMISSION_DENIED: "PERMISSION_DENIED",
  CONCURRENCY_CONFLICT: "CONCURRENCY_CONFLICT",

  // 租户相关错误代码
  TENANT_NAME_ALREADY_EXISTS: "TENANT_NAME_ALREADY_EXISTS",
  INVALID_TENANT_TYPE: "INVALID_TENANT_TYPE",
  TENANT_NOT_FOUND: "TENANT_NOT_FOUND",

  // 组织相关错误代码
  ORGANIZATION_NAME_ALREADY_EXISTS: "ORGANIZATION_NAME_ALREADY_EXISTS",
  INVALID_ORGANIZATION_TYPE: "INVALID_ORGANIZATION_TYPE",
  ORGANIZATION_NOT_FOUND: "ORGANIZATION_NOT_FOUND",

  // 部门相关错误代码
  DEPARTMENT_NAME_ALREADY_EXISTS: "DEPARTMENT_NAME_ALREADY_EXISTS",
  INVALID_DEPARTMENT_LEVEL: "INVALID_DEPARTMENT_LEVEL",
  DEPARTMENT_NOT_FOUND: "DEPARTMENT_NOT_FOUND",

  // 用户相关错误代码
  USER_EMAIL_ALREADY_EXISTS: "USER_EMAIL_ALREADY_EXISTS",
  USER_USERNAME_ALREADY_EXISTS: "USER_USERNAME_ALREADY_EXISTS",
  INVALID_USER_STATUS: "INVALID_USER_STATUS",
  USER_NOT_FOUND: "USER_NOT_FOUND",

  // 角色相关错误代码
  ROLE_NAME_ALREADY_EXISTS: "ROLE_NAME_ALREADY_EXISTS",
  ROLE_NOT_FOUND: "ROLE_NOT_FOUND",

  // 权限相关错误代码
  PERMISSION_NAME_ALREADY_EXISTS: "PERMISSION_NAME_ALREADY_EXISTS",
  PERMISSION_NOT_FOUND: "PERMISSION_NOT_FOUND",
} as const;

/**
 * 错误严重级别常量
 */
export const ErrorSeverity = {
  /** 低级别错误 */
  LOW: "LOW",
  /** 中级别错误 */
  MEDIUM: "MEDIUM",
  /** 高级别错误 */
  HIGH: "HIGH",
  /** 严重错误 */
  CRITICAL: "CRITICAL",
} as const;

/**
 * 错误类型常量
 */
export const ErrorTypes = {
  /** 验证错误 */
  VALIDATION: "VALIDATION",
  /** 业务规则错误 */
  BUSINESS_RULE: "BUSINESS_RULE",
  /** 状态错误 */
  STATE: "STATE",
  /** 权限错误 */
  PERMISSION: "PERMISSION",
  /** 并发错误 */
  CONCURRENCY: "CONCURRENCY",
  /** 未找到错误 */
  NOT_FOUND: "NOT_FOUND",
} as const;
