openapi: 3.0.3
info:
  title: Exception System Enhancement API
  description: API contracts for the enhanced exception handling system
  version: 1.0.0
  contact:
    name: HL8 SAAS Platform Team
    email: team@hl8.com

servers:
  - url: https://api.hl8.com/v1
    description: Production server
  - url: https://staging-api.hl8.com/v1
    description: Staging server

paths:
  /exceptions:
    get:
      summary: List all exception classes
      description: Retrieve all available exception classes with optional filtering
      parameters:
        - name: category
          in: query
          description: Filter by exception category
          schema:
            type: string
            enum:
              [
                auth,
                user,
                tenant,
                organization,
                department,
                validation,
                business,
                system,
                integration,
                general,
              ]
        - name: layer
          in: query
          description: Filter by architecture layer
          schema:
            type: string
            enum: [interface, application, domain, infrastructure]
        - name: status
          in: query
          description: Filter by exception status
          schema:
            type: string
            enum: [active, deprecated, draft]
        - name: limit
          in: query
          description: Maximum number of results
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: offset
          in: query
          description: Number of results to skip
          schema:
            type: integer
            minimum: 0
            default: 0
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/ExceptionClass"
                  pagination:
                    $ref: "#/components/schemas/Pagination"
        "400":
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
        "500":
          description: Internal server error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"

  /exceptions/{errorCode}:
    get:
      summary: Get exception class by error code
      description: Retrieve a specific exception class by its error code
      parameters:
        - name: errorCode
          in: path
          required: true
          description: The error code of the exception class
          schema:
            type: string
            pattern: "^[A-Z_]+$"
            example: "AUTH_LOGIN_FAILED"
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/ExceptionClass"
        "404":
          description: Exception class not found
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
        "500":
          description: Internal server error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"

  /exceptions/{errorCode}/messages:
    get:
      summary: Get exception messages
      description: Retrieve localized messages for a specific exception class
      parameters:
        - name: errorCode
          in: path
          required: true
          description: The error code of the exception class
          schema:
            type: string
            pattern: "^[A-Z_]+$"
        - name: language
          in: query
          description: Language code for messages
          schema:
            type: string
            default: "zh-CN"
            enum: [zh-CN, en-US]
        - name: messageType
          in: query
          description: Type of message to retrieve
          schema:
            type: string
            enum: [title, detail]
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/ExceptionMessage"
        "404":
          description: Exception class not found
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
        "500":
          description: Internal server error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"

  /exceptions/categories:
    get:
      summary: List exception categories
      description: Retrieve all available exception categories
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/ExceptionCategory"
        "500":
          description: Internal server error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"

  /exceptions/layers:
    get:
      summary: List architecture layers
      description: Retrieve all Clean Architecture layers
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/ArchitectureLayer"
        "500":
          description: Internal server error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"

components:
  schemas:
    ExceptionClass:
      type: object
      required:
        - id
        - name
        - errorCode
        - title
        - defaultDetail
        - httpStatus
        - categoryId
        - layerId
        - isDeprecated
        - createdAt
        - updatedAt
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the exception class
        name:
          type: string
          description: Exception class name
          example: "AuthenticationFailedException"
        errorCode:
          type: string
          description: Unique error code
          pattern: "^[A-Z_]+$"
          example: "AUTH_LOGIN_FAILED"
        title:
          type: string
          description: Brief error title in Chinese
          example: "认证失败"
        defaultDetail:
          type: string
          description: Default error detail message in Chinese
          example: "用户名或密码错误"
        httpStatus:
          type: integer
          description: HTTP status code
          minimum: 100
          maximum: 599
          example: 401
        categoryId:
          type: string
          format: uuid
          description: Reference to exception category
        layerId:
          type: string
          format: uuid
          description: Reference to architecture layer
        isDeprecated:
          type: boolean
          description: Whether the exception is deprecated
          default: false
        createdAt:
          type: string
          format: date-time
          description: Creation timestamp
        updatedAt:
          type: string
          format: date-time
          description: Last update timestamp

    ExceptionCategory:
      type: object
      required:
        - id
        - name
        - displayName
        - description
        - prefix
        - layer
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the category
        name:
          type: string
          description: Category name
          example: "auth"
        displayName:
          type: string
          description: Human-readable display name in Chinese
          example: "认证授权"
        description:
          type: string
          description: Category description in Chinese
          example: "处理认证和授权相关的异常"
        prefix:
          type: string
          description: Error code prefix
          example: "AUTH_"
        layer:
          type: string
          description: Associated Clean Architecture layer
          enum: [interface, application, domain, infrastructure]
          example: "interface"

    ArchitectureLayer:
      type: object
      required:
        - id
        - name
        - displayName
        - description
        - order
        - baseClassName
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the layer
        name:
          type: string
          description: Layer name
          enum: [interface, application, domain, infrastructure]
          example: "interface"
        displayName:
          type: string
          description: Human-readable display name in Chinese
          example: "接口层"
        description:
          type: string
          description: Layer description in Chinese
          example: "处理HTTP请求和响应的接口层"
        order:
          type: integer
          description: Layer order in architecture
          minimum: 1
          maximum: 4
          example: 1
        baseClassName:
          type: string
          description: Base exception class name for this layer
          example: "InterfaceLayerException"

    ExceptionMessage:
      type: object
      required:
        - id
        - exceptionClassId
        - language
        - messageType
        - content
        - parameters
        - isDefault
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the message
        exceptionClassId:
          type: string
          format: uuid
          description: Reference to exception class
        language:
          type: string
          description: Language code
          enum: [zh-CN, en-US]
          example: "zh-CN"
        messageType:
          type: string
          description: Message type
          enum: [title, detail]
          example: "title"
        content:
          type: string
          description: Message content with parameter placeholders
          example: "用户 {{userId}} 认证失败"
        parameters:
          type: array
          description: Available parameter names for substitution
          items:
            type: string
          example: ["userId", "reason"]
        isDefault:
          type: boolean
          description: Whether this is the default message for the type
          default: false

    ProblemDetails:
      type: object
      required:
        - type
        - title
        - detail
        - status
        - errorCode
      properties:
        type:
          type: string
          format: uri
          description: Error type URI reference
          example: "https://docs.hl8.com/errors#AUTH_LOGIN_FAILED"
        title:
          type: string
          description: Brief error title
          example: "认证失败"
        detail:
          type: string
          description: Detailed error description
          example: "用户名或密码错误"
        status:
          type: integer
          description: HTTP status code
          example: 401
        errorCode:
          type: string
          description: Application-specific error code
          example: "AUTH_LOGIN_FAILED"
        instance:
          type: string
          description: Request instance identifier
          example: "req-123456"
        data:
          type: object
          description: Additional error context data
          additionalProperties: true

    Pagination:
      type: object
      required:
        - limit
        - offset
        - total
        - hasMore
      properties:
        limit:
          type: integer
          description: Maximum number of results per page
          example: 20
        offset:
          type: integer
          description: Number of results skipped
          example: 0
        total:
          type: integer
          description: Total number of results
          example: 150
        hasMore:
          type: boolean
          description: Whether there are more results available
          example: true

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token authentication

security:
  - BearerAuth: []

tags:
  - name: Exceptions
    description: Exception class management and retrieval
  - name: Categories
    description: Exception category management
  - name: Layers
    description: Architecture layer management
